### ISSUE TITLE
prj should be taken from source file

### ISSUE THREAD

**Issue by pcav** [dtutic/CartoLineGen#4]
The plugin asks (twice, why two output?) for projection of the layer to be loaded.
The projection should be taken from source file, without intervention from the user.

**Comment by pcav** [comment]
The prj is in fact generated, but placed in a dir above the one where shp is.

**Comment by dtutic** [comment]
Thanks. Which version of QGIS, since in 2.14 I do not have this message.

**Comment by dtutic** [comment]
prj file is created from source file in destination path:

 #create .prj file
    spatialRef = inLayer.GetSpatialRef()
    spatialRef.MorphToESRI()
    file = open(os.path.splitext(outFile)[0]+'.prj', 'w')
    file.write(spatialRef.ExportToWkt())
    file.close()
