### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by pcav** [dtutic/CartoLineGen#5]
See attached.
[wss.zip](https://github.com/dtutic/CartoLineGen/files/287642/wss.zip)

**Comment by dtutic** [comment]
Please send me the input data. Forcing area preservation in equations can
give such results (new points in "infinity"). I tried to take care of all
special cases but it obviously is not robust enough yet.

**Comment by pcav** [comment]
https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/training_manual/exercise_data/processing/generalize

**Comment by dtutic** [comment]
Fixed in generalize.py. Problem raised when some parallel segments appeared, or points lie on line. The sample set is now generalized as expected.

**Comment by pcav** [comment]
Thanks. Please let me know when you upload a new version.
